# Save as .codeclimate.yml (note leading .) in project root directory
languages:
  Ruby: true
  JavaScript: true
  PHP: true
  Python: true
exclude_paths:
 - bower_components/**/*
 - node_modules/**/*
 - **.spec.js