language: node_js
node_js:
- '0.10'
before_script:
- npm install -g bower
- npm install -g gulp
- npm install phantomjs
- npm install -g karma
- npm install -g typescript@1.4.1
- bower install
- gulp build
deploy:
  provider: heroku
  api_key:
    secure: f6Wchkz7QpchC6VFIzA24hfUVovgXBaZAPXemYdumx1jP+bmzO0fEPqTN5vQDJV/WM9U5esCXCbS91JL0OP51nXhbHFlcmhtLSG2YjyNVpj3ntfDp9QlAE5lQTTxpqUHUcWtTY/ZZYEliflXXPHYjLP4KCDWZ+0iMMyUMf9DGG6/S2hA9v+Mit+uAcKwI2I9dwaWC4cZtuEC83HbBgJgOGT/Y2KVNphiqIsadlisGqpK+i0C6uAfNrsn4cQcVBr9PtBXO0ROqOP1jDHtp86yIXDepN3LOkwj9ntqd5QdOXZjqfT+ugCBQUdKxUPOrzI8wJcR8ap5bloBUJA24Qj/o3hc9oIkvD1mJryuwHuTC0h/5fPxw0ipcHx2St6oT2pZ6viDpB8Dvfq4OeglSyI+27EmvR2B5mqFzcpKn0st0aAuEdNPnQ6xugOOzWwyl03dyEFmtOGhH5BZyAf3xbO9+S0oaCZi+OFOfwG1W0Mj5vw5Xn89M1HPs0RXEMKeH5CmcJdHFHhHmUX6oV7M5l8VvOl4s9ldB4ESHN7xIKoi+LRa0fFwjg4iOqW5yJDpCCRrsBBYm4o22NjS+2+7JQaZFBRM4c9/jqr168XfnEyvSvMQ/eOXWRtDpwNZYUZ17D0Ye6SlZzzAYUHWmrxupzM1Td2T0lkVEQU+k+mMkP/mZmg=
  app: pyramidionopenfdadev
  on:
    repo: PyramidSystemsInc/ADS-Dev
    branch: dev
